Iskhakov/fix frontend tests (#1878)
# What this PR does
```
    /Users/ildariskhakov/src/github.com/grafana/oncall/grafana-plugin/node_modules/@grafana/ui/node_modules/uplot/dist/uPlot.cjs.js:3570
    		stroke ??= transparent;
    		       ^^^

    SyntaxError: Unexpected token '??='
```
#### Fix
upgrade to node 16 
OR
add `uplot` to `transformIgnorePatterns`
## Which issue(s) this PR fixes

## Checklist

- [ ] Unit, integration, and e2e (if applicable) tests updated
- [ ] Documentation added (or `pr:no public docs` PR label added if not
required)
- [ ] `CHANGELOG.md` updated (or `pr:no changelog` PR label added if not
required)